name: Ubuntu VPS
on:
  workflow_dispatch:
jobs:
  vps:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
