name: Ubuntu VPS
on:
  workflow_dispatch:
jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Start SSH session (tmate)
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false   # <-- QUAN TRỌNG: tắt kiểm tra SSH key
